removed failing test
since 67a96d51f3d038d1ed69545e9e9c618b0f969408, the iQvoc core does not
provide a rankable relation class anymore - so a one needs to be created
for testing

however, while the following code works in development mode, it throws
NoMethodError ("undefined method `concept_relation_weighteds'") in test
mode - even after `cp lib/iqvoc/environments/{development,test}.rb`

    class Concept::Relation::Weighted < Concept::Relation::Base
      include Iqvoc::Rankable
    end
    Iqvoc::Concept.further_relation_class_names << "Concept::Relation::Weighted"
    concept = Iqvoc::Concept.base_class.new
    concept.concept_relation_weighteds.new